services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "clickhouse-client --user clickhouse --password clickhouse --query 'SELECT 1'",
        ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  clickhouse-data:
